language: node_js
node_js:
  - "0.10"
script: npm run-script test-travis
before_script:
  - mysql -e 'create database shed;'
after_script:
- npm install -g coveralls@2
- cat ./coverage/lcov.info | coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6a25fffd6b0def418989
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
